import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import App from "../layouts/app";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const font = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" suppressContentEditableWarning>
      <App
        hostname={process.env.PUBLIC_URL!}
        bodyClassName={cn("min-h-screen bg-background font-sans antialiased", font.variable)}
      >
        {children}
      </App>
    </html>
  );
}
